name: Deploy to Vercel and Analyze with SonarCloud - project framework angular

on:
  push:
    branches:
      - master

jobs:
  build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration=production

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ANGULAR_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Deploy to Vercel
        uses: vercel/action@v21.2.1
        with:
          github_token: ${{ secrets.ANGULAR_GITHUB_TOKEN }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}